### PR TITLE
updated index.html due to removal StateMarketDeals, enhanced index.html

### PR DESCRIPTION
**Pull request by mur-me**
What was done:
updated index.html:
added a notice about StateMarketDeals operation,
added S3 link to StateMarketDeals operation,
added some css style, tables and some small logos,
updated v0.html and v1.html due to content-typeapplication/json in response

### CODE REVIEW

**Comment by mur-me** [comment]
image
How it looks like in browser

**Comment by ArseniiPetrovich** [comment]
@mur-me can we have Glif logo right to the Protofire logo?
We can also say "hosted by protofire team in conjunction with the Glif team"

**Comment by mur-me** [comment]
@ArseniiPetrovich will add this!

**Comment by mur-me** [comment]
Now it is better @ArseniiPetrovich 
image

**Review by ArseniiPetrovich — APPROVED** [review]

**Pull request merged**
